"""Frozen natural-batch protocol; no threshold is selected from RAGTruth labels."""

PROTOCOL = {
    "schema": "native-audit/protocol@3",
    "anchor_schema": "verbatim-clause-target-mask@1",
    "cloze_unparsed_context": "all_alphanumeric_surface_fragments_are_required_conditions",
    "reader_json_parser": "intact-first-root-terminal-punctuation@1",
    "condition_quote_binding": "exact_role_response_span_and_digest_verified_sidecar",
    "reader_request_accounting": "all_returns_including_cache_hits; failures_never_recovered",
    "atomic_frames_per_batch": 24,
    "atomic_frames_per_response": 48,
    "atomic_batches_per_response": 8,
    "atomic_frame_json_token_limit": 3072,
    "atomic_units_per_batch": 4,
    "atomic_role_word_limit": 16,
    "atomic_predicate_word_limit": 6,
    "atomic_condition_table": "exact_exhaustive_role_binding",
    "reader_source_json_token_limit": 1536,
    "semantic_threshold": 0.8,
    "effect_threshold_nats": 0.5,
    "selectivity_threshold_nats": 0.25,
    "repeat_tolerance_nats": 1e-5,
    "question_limit": 48,
    "claims_per_response": 4,
    "forwards_per_claim": 320,
    "forwards_per_response": 1280,
    "native_input_limit": 4096,
    "reader_context_limit": 8192,
    "continuation_limit": 96,
    "control_pool_limit": 16,
    "candidate_labels": [
        "applicable",
        "contradictory",
        "nonapplicable",
        "unrelated",
        "uncertain",
    ],
    "semantic_states": ["supported", "unsupported", "uncertain", "invalid_question"],
    "coverage_states": ["assertion", "nonassertion", "coverage_unknown"],
    "relations": ["same_claim", "elaboration", "correction", "new_claim", "unknown"],
    "phase_order": ["A", "B", "C", "D", "merge"],
    "validation_order": {
        "C_or_supported_recovery": [
            "position",
            "origin",
            "paired_role",
            "MLP_interaction",
            "layer_bands",
        ],
        "N": ["position", "origin", "N_template", "layer_bands"],
    },
    "N_template_scope": "one_primary_position_and_its_origin; other_mechanisms_unresolved",
    "labels_used": False,
    "observer_replay_not_original_generator_internal_trace": True,
    "reader_predictions_not_ground_truth": True,
}
